version: "3.3"
services: 
    mongodb:
        image: mongo
        container_name: "mongodbRTA"
    qrs:
        image: qhose/qlikracingrta:1.0.0
        environment:
            - MONGO_URL=mongodb://mongodb:27017/
            - PORT=3000 
            - ROOT_URL=http://localhost
        ports:
        -  "3000:3000"
        restart: always
        links:
        - mongodb
        depends_on:
        - mongodb
networks:
    default: